"""
report_generator.py — HomeFi PDF Report Generator
Generates a professional multi-page PDF report with charts and financial summary.
Usage: Called from main.py (Option 12) or run directly.
"""

import os
from datetime import datetime

# ReportLab imports
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


# ── Colour palette ──────────────────────────────────────────────────────────
DARK_BG    = colors.HexColor("#1a1a2e")
ACCENT     = colors.HexColor("#00d4aa")
ACCENT2    = colors.HexColor("#f4a261")
LIGHT_GREY = colors.HexColor("#f5f5f5")
MID_GREY   = colors.HexColor("#cccccc")
DARK_GREY  = colors.HexColor("#333333")
WHITE      = colors.white
RED        = colors.HexColor("#e63946")
GREEN      = colors.HexColor("#2dc653")


# ── Custom styles ────────────────────────────────────────────────────────────
def _build_styles():
    base = getSampleStyleSheet()

    styles = {
        "cover_title": ParagraphStyle(
            "cover_title", parent=base["Title"],
            fontSize=36, textColor=WHITE, alignment=TA_CENTER,
            spaceAfter=6, fontName="Helvetica-Bold"
        ),
        "cover_sub": ParagraphStyle(
            "cover_sub", parent=base["Normal"],
            fontSize=14, textColor=ACCENT, alignment=TA_CENTER,
            spaceAfter=4
        ),
        "cover_date": ParagraphStyle(
            "cover_date", parent=base["Normal"],
            fontSize=11, textColor=MID_GREY, alignment=TA_CENTER
        ),
        "section_head": ParagraphStyle(
            "section_head", parent=base["Heading1"],
            fontSize=16, textColor=ACCENT, fontName="Helvetica-Bold",
            spaceBefore=14, spaceAfter=6, borderPad=4
        ),
        "sub_head": ParagraphStyle(
            "sub_head", parent=base["Heading2"],
            fontSize=12, textColor=DARK_GREY, fontName="Helvetica-Bold",
            spaceBefore=10, spaceAfter=4
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"],
            fontSize=10, textColor=DARK_GREY,
            spaceAfter=4, leading=15
        ),
        "tip": ParagraphStyle(
            "tip", parent=base["Normal"],
            fontSize=10, textColor=colors.HexColor("#1b4332"),
            spaceAfter=3, leading=14,
            leftIndent=8
        ),
        "footer": ParagraphStyle(
            "footer", parent=base["Normal"],
            fontSize=8, textColor=MID_GREY, alignment=TA_CENTER
        ),
    }
    return styles


# ── Header / Footer callbacks ─────────────────────────────────────────────
def _on_page(canvas, doc):
    """Draws header bar and footer on every page except cover."""
    w, h = A4
    page_num = doc.page

    if page_num == 1:          # cover page — no header/footer
        return

    # Top accent bar
    canvas.saveState()
    canvas.setFillColor(DARK_BG)
    canvas.rect(0, h - 1.2 * cm, w, 1.2 * cm, fill=1, stroke=0)
    canvas.setFillColor(ACCENT)
    canvas.rect(0, h - 1.25 * cm, w, 0.12 * cm, fill=1, stroke=0)

    # Header text
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(1.5 * cm, h - 0.85 * cm, "HomeFi — Household Finance Report")
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(ACCENT)
    canvas.drawRightString(w - 1.5 * cm, h - 0.85 * cm,
                           datetime.now().strftime("%d %b %Y"))

    # Bottom footer
    canvas.setFillColor(MID_GREY)
    canvas.rect(1.5 * cm, 0.8 * cm, w - 3 * cm, 0.04 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.HexColor("#888888"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(1.5 * cm, 0.45 * cm, "Generated by HomeFi Analyzer")
    canvas.drawRightString(w - 1.5 * cm, 0.45 * cm, f"Page {page_num - 1}")
    canvas.restoreState()


# ── Cover page ────────────────────────────────────────────────────────────
def _cover_page(styles):
    w, h = A4
    elements = []

    # Dark background rectangle drawn via a Table trick
    cover_data = [[""]]
    cover_table = Table(cover_data, colWidths=[w - 4 * cm], rowHeights=[5 * cm])
    cover_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), DARK_BG),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [DARK_BG]),
    ]))

    elements.append(Spacer(1, 3 * cm))
    elements.append(Paragraph("HomeFi", styles["cover_title"]))
    elements.append(Paragraph("Household Finance Analyzer", styles["cover_sub"]))
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(HRFlowable(width="60%", thickness=2, color=ACCENT,
                                spaceBefore=4, spaceAfter=8, hAlign="CENTER"))
    elements.append(Paragraph(
        "Personal Finance Report — Income, Expenses, Savings & Forecast",
        styles["cover_sub"]
    ))
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        styles["cover_date"]
    ))
    elements.append(PageBreak())
    return elements


# ── Summary table ─────────────────────────────────────────────────────────
def _summary_section(summary: dict, styles):
    elements = []
    elements.append(Paragraph("1. Financial Summary", styles["section_head"]))
    elements.append(HRFlowable(width="100%", thickness=1,
                                color=ACCENT, spaceAfter=10))

    rows = [
        ["Metric", "Value"],
        ["Total Income",    f"Rs. {summary.get('total_income', 0):,.0f}"],
        ["Total Expenses",  f"Rs. {summary.get('total_expense', 0):,.0f}"],
        ["Net Savings",     f"Rs. {summary.get('net_savings', 0):,.0f}"],
        ["Savings Rate",    f"{summary.get('savings_rate', 0):.1f}%"],
        ["Months Covered",  str(summary.get('months', 'N/A'))],
        ["Best Month",      summary.get('best_month', 'N/A')],
        ["Worst Month",     summary.get('worst_month', 'N/A')],
    ]

    col_w = [(A4[0] - 4 * cm) * f for f in (0.55, 0.45)]
    tbl = Table(rows, colWidths=col_w)
    tbl.setStyle(TableStyle([
        # Header row
        ("BACKGROUND",  (0, 0), (-1, 0), DARK_BG),
        ("TEXTCOLOR",   (0, 0), (-1, 0), ACCENT),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0), 11),
        ("ALIGN",       (0, 0), (-1, 0), "CENTER"),
        # Data rows
        ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 1), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GREY]),
        ("TEXTCOLOR",   (0, 1), (0, -1), DARK_GREY),
        ("TEXTCOLOR",   (1, 1), (1, -1), colors.HexColor("#0d6efd")),
        ("FONTNAME",    (1, 1), (1, -1), "Helvetica-Bold"),
        ("ALIGN",       (1, 1), (-1, -1), "RIGHT"),
        # Grid
        ("GRID",        (0, 0), (-1, -1), 0.5, MID_GREY),
        ("TOPPADDING",  (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(tbl)

    # Savings health badge
    rate = summary.get("savings_rate", 0)
    if rate >= 30:
        badge_col, badge_txt = GREEN,  "Savings Health: EXCELLENT (>30%)"
    elif rate >= 20:
        badge_col, badge_txt = ACCENT, "Savings Health: GOOD (20-30%)"
    elif rate >= 10:
        badge_col, badge_txt = ACCENT2,"Savings Health: AVERAGE (10-20%)"
    else:
        badge_col, badge_txt = RED,    "Savings Health: NEEDS IMPROVEMENT (<10%)"

    badge_data = [[badge_txt]]
    badge_tbl = Table(badge_data, colWidths=[A4[0] - 4 * cm])
    badge_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), badge_col),
        ("TEXTCOLOR",     (0, 0), (-1, -1), WHITE),
        ("FONTNAME",      (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 11),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(Spacer(1, 0.4 * cm))
    elements.append(badge_tbl)
    return elements


# ── Chart section helper ──────────────────────────────────────────────────
def _chart_section(title: str, section_num: int, charts: list[tuple],
                   description: str, styles):
    """
    charts: list of (filepath, caption) tuples
    """
    elements = []
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph(f"{section_num}. {title}", styles["section_head"]))
    elements.append(HRFlowable(width="100%", thickness=1,
                                color=ACCENT, spaceAfter=8))
    if description:
        elements.append(Paragraph(description, styles["body"]))
        elements.append(Spacer(1, 0.3 * cm))

    usable_w = A4[0] - 4 * cm  # page width minus margins

    for (chart_path, caption) in charts:
        if chart_path and os.path.exists(chart_path):
            img = Image(chart_path, width=usable_w, height=usable_w * 0.55)
            elements.append(img)
            if caption:
                cap_style = ParagraphStyle(
                    "cap", parent=styles["body"],
                    fontSize=9, textColor=colors.HexColor("#666666"),
                    alignment=TA_CENTER, spaceAfter=10
                )
                elements.append(Paragraph(f"<i>{caption}</i>", cap_style))
            elements.append(Spacer(1, 0.4 * cm))
        else:
            elements.append(Paragraph(
                f"[Chart not found: {chart_path}]", styles["body"]
            ))
    return elements


# ── Recommendations section ───────────────────────────────────────────────
def _recommendations_section(tips: list[str], styles):
    elements = []
    elements.append(PageBreak())
    elements.append(Paragraph("7. Smart Recommendations", styles["section_head"]))
    elements.append(HRFlowable(width="100%", thickness=1,
                                color=ACCENT, spaceAfter=8))
    elements.append(Paragraph(
        "Based on your spending patterns, here are personalised tips to "
        "improve your financial health:",
        styles["body"]
    ))
    elements.append(Spacer(1, 0.3 * cm))

    icons = ["[!]", "[>]", "[*]", "[#]", "[$]", "[~]"]
    for i, tip in enumerate(tips):
        icon = icons[i % len(icons)]
        elements.append(Paragraph(f"{icon}  {tip}", styles["tip"]))
        elements.append(Spacer(1, 0.15 * cm))

    if not tips:
        elements.append(Paragraph(
            "Great job! No critical recommendations at this time. "
            "Keep maintaining your spending discipline.",
            styles["tip"]
        ))
    return elements


# ── Forecast section ─────────────────────────────────────────────────────
def _forecast_section(forecast_data: dict, styles):
    elements = []
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph("5. Expense Forecast", styles["section_head"]))
    elements.append(HRFlowable(width="100%", thickness=1,
                                color=ACCENT, spaceAfter=8))

    predicted = forecast_data.get("predicted_expense", 0)
    trend     = forecast_data.get("trend", "stable")
    change    = forecast_data.get("monthly_change", 0)

    summary_txt = (
        f"Based on linear regression over your historical data, next month's "
        f"predicted total expense is <b>Rs. {predicted:,.0f}</b>. "
        f"Your spending trend is <b>{trend.upper()}</b> "
        f"with an average monthly change of Rs. {abs(change):,.0f}."
    )
    elements.append(Paragraph(summary_txt, styles["body"]))
    return elements


# ── Goals section ────────────────────────────────────────────────────────
def _goals_section(goals: list[dict], styles):
    elements = []
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph("6. Savings Goals", styles["section_head"]))
    elements.append(HRFlowable(width="100%", thickness=1,
                                color=ACCENT, spaceAfter=8))

    if not goals:
        elements.append(Paragraph("No goals set yet. Add goals via the CLI menu.",
                                   styles["body"]))
        return elements

    rows = [["Goal", "Target (Rs.)", "Saved (Rs.)", "Progress", "ETA"]]
    for g in goals:
        pct = min(100, (g.get("saved", 0) / g.get("target", 1)) * 100)
        bar = ("█" * int(pct / 10)).ljust(10, "░")
        rows.append([
            g.get("name", "—"),
            f"{g.get('target', 0):,.0f}",
            f"{g.get('saved', 0):,.0f}",
            f"{bar} {pct:.0f}%",
            g.get("eta", "—"),
        ])

    col_w = [(A4[0] - 4*cm) * f for f in (0.28, 0.16, 0.16, 0.24, 0.16)]
    tbl = Table(rows, colWidths=col_w)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), DARK_BG),
        ("TEXTCOLOR",     (0, 0), (-1, 0), ACCENT),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 10),
        ("ALIGN",         (0, 0), (-1, 0), "CENTER"),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 9),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT_GREY]),
        ("ALIGN",         (1, 1), (-1, -1), "CENTER"),
        ("GRID",          (0, 0), (-1, -1), 0.5, MID_GREY),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]))
    elements.append(tbl)
    return elements


# ── Main generate function ────────────────────────────────────────────────
def generate_report(
    summary: dict         = None,
    forecast_data: dict   = None,
    goals: list           = None,
    tips: list            = None,
    charts_dir: str       = "Charts",
    reports_dir: str      = "Reports",
    filename: str         = None,
):
    """
    Generate the HomeFi PDF report.

    Parameters
    ----------
    summary       : dict from analyzer.get_summary()
    forecast_data : dict from forecaster.get_forecast_data()
    goals         : list of goal dicts from goals.load_goals()
    tips          : list of tip strings from recommender.get_tips()
    charts_dir    : path to Charts/ folder
    reports_dir   : path to Reports/ folder
    filename      : output PDF filename (auto-generated if None)
    """
    summary       = summary       or {}
    forecast_data = forecast_data or {}
    goals         = goals         or []
    tips          = tips          or []

    os.makedirs(reports_dir, exist_ok=True)

    if filename is None:
        ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"HomeFi_Report_{ts}.pdf"

    out_path = os.path.join(reports_dir, filename)

    doc = SimpleDocTemplate(
        out_path,
        pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=1.8 * cm, bottomMargin=1.8 * cm,
        title="HomeFi Financial Report",
        author="HomeFi Analyzer",
    )

    styles   = _build_styles()
    story    = []

    # ── 1. Cover ──────────────────────────────────────────────────────
    story += _cover_page(styles)

    # ── 2. Financial Summary ──────────────────────────────────────────
    story += _summary_section(summary, styles)

    # ── 3. Category Analysis ──────────────────────────────────────────
    story.append(PageBreak())
    story += _chart_section(
        title       = "Category-wise Spending",
        section_num = 2,
        charts      = [
            (os.path.join(charts_dir, "category_pie.png"),
             "Category distribution of total expenses"),
            (os.path.join(charts_dir, "category_bar.png"),
             "Horizontal bar chart — category spending breakdown"),
        ],
        description = (
            "The charts below show how your total expenses are distributed "
            "across different categories over the analysis period."
        ),
        styles=styles,
    )

    # ── 4. Monthly Trends ─────────────────────────────────────────────
    story.append(PageBreak())
    story += _chart_section(
        title       = "Monthly Trends",
        section_num = 3,
        charts      = [
            (os.path.join(charts_dir, "trend_line.png"),
             "Income vs Expenses vs Savings — month by month"),
            (os.path.join(charts_dir, "savings_rate.png"),
             "Monthly savings rate vs 20% target line"),
        ],
        description = (
            "Track how your income, expenses, and savings have changed "
            "every month. The 20% line on the savings chart is a "
            "recommended minimum savings target."
        ),
        styles=styles,
    )

    # ── 5. Budget vs Actual ───────────────────────────────────────────
    story.append(PageBreak())
    story += _chart_section(
        title       = "Budget vs Actual",
        section_num = 4,
        charts      = [
            (os.path.join(charts_dir, "budget_vs_actual.png"),
             "Budget limits vs actual spending per category"),
        ],
        description = (
            "Compare what you planned to spend (budget) vs what you "
            "actually spent. Red bars indicate budget exceeded."
        ),
        styles=styles,
    )

    # ── 6. Forecast ───────────────────────────────────────────────────
    story += _forecast_section(forecast_data, styles)
    story += _chart_section(
        title       = "",
        section_num = 0,   # blank, heading already added above
        charts      = [
            (os.path.join(charts_dir, "forecast.png"),
             "Historical expense trend with next-month prediction (red dot)"),
        ],
        description = "",
        styles=styles,
    )

    # ── 7. Goals ──────────────────────────────────────────────────────
    story += _goals_section(goals, styles)
    story += _chart_section(
        title       = "",
        section_num = 0,
        charts      = [
            (os.path.join(charts_dir, "goals_progress.png"),
             "Savings goals progress tracker"),
        ],
        description = "",
        styles=styles,
    )

    # ── 8. Spending Health ────────────────────────────────────────────
    story.append(PageBreak())
    story += _chart_section(
        title       = "Spending Health (50-30-20 Rule)",
        section_num = 6,
        charts      = [
            (os.path.join(charts_dir, "spending_health.png"),
             "Actual vs Warning vs Danger thresholds for each category"),
        ],
        description = (
            "The 50-30-20 rule recommends: 50% on Needs, 30% on Wants, "
            "20% on Savings. Green bars are within limits; red bars need "
            "attention."
        ),
        styles=styles,
    )

    # ── 9. Recommendations ───────────────────────────────────────────
    story += _recommendations_section(tips, styles)

    # ── Build ─────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    print(f"\n[OK] PDF report saved: {out_path}")
    return out_path


# ── Standalone test ──────────────────────────────────────────────────────
if __name__ == "__main__":
    # Mock data — replace with real module calls in main.py
    test_summary = {
        "total_income":  295000,
        "total_expense": 177400,
        "net_savings":   117600,
        "savings_rate":  39.86,
        "months":        6,
        "best_month":    "Apr 2024 (Rs.27,090 | 47.5%)",
        "worst_month":   "Mar 2024 (Rs.32,770)",
    }
    test_forecast = {
        "predicted_expense": 33138,
        "trend":             "increasing",
        "monthly_change":    1021,
    }
    test_goals = [
        {"name": "Emergency Fund",  "target": 100000, "saved": 35000, "eta": "8 months"},
        {"name": "Laptop",          "target":  60000, "saved": 20000, "eta": "5 months"},
        {"name": "Vacation",        "target":  80000, "saved": 10000, "eta": "14 months"},
    ]
    test_tips = [
        "Food spending is 28% of expenses — aim to bring it below 25%.",
        "Entertainment budget exceeded by Rs. 1,200 last month.",
        "Your savings rate of 39.86% is excellent — consider investing the surplus.",
        "EMI payments are 18% of income — avoid taking new loans.",
        "Set up an auto-transfer on salary day to lock in savings before spending.",
        "Your spending trend is increasing by Rs. 1,021/month — review discretionary items.",
    ]

    generate_report(
        summary       = test_summary,
        forecast_data = test_forecast,
        goals         = test_goals,
        tips          = test_tips,
        charts_dir    = "Charts",
        reports_dir   = "Reports",
    )